apiVersion: 1
swaggerVersion: 1.2
basePath: 'http://www.stori.es/api/website/listings'
description: 'organization-specific user profiles'
resourcePath: '/profiles'
produces:
  - 'application/vnd.api+json'
consumes:
  - 'application/vnd.api+json'
apis:
  -
    path: '/profiles'
    operations:          
      -
        method: 'POST'
        summary: 'Create a new profile'
        notes: 'Creates a new profile and returns it. Declares the resource URL in the <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30" title="HTTP 1.1 Header Fields - Location">HTTP Location header</a>.'
        type: 'ApiResponse'
        nickname: 'create_profile'
        parameters:
          -
            name: 'body'
            description: 'The new profile to be created'
            required: true
            type: 'ProfilePost'
            paramType: 'body'
        responseMessages:
          -
            code: 201
            message: 'Resource successfully created'
            responseModel: 'ApiResponse'
          -
            code: 400
            message: 'Invalid input'
            responseModel: 'ApiResponse'
          -
            code: 403
            message: 'Not authorized to create the requested resource'
            responseModel: 'ApiResponse'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'ApiResponse'
  -
    path: '/profiles/{profile_id}'
    operations:
      -
        method: 'GET'
        summary: 'Retrieve a specific profile'
        notes: 'Returns a specific profile accessible to the current user'
        type: 'ApiResponse'
        nickname: 'get_profile'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to retrieve'
            required: true
            type: 'string'
            paramType: 'path'
        responseMessages:
          -
            code: 200
            message: 'Resource successfully retrieved'
            responseModel: 'ApiResponse'
          -
            code: 403
            message: 'Not authorized to access the requested resource'
            responseModel: 'ApiResponse'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'ApiResponse'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'ApiResponse'
      -
        method: 'DELETE'
        summary: 'Delete a profile'
        notes: 'Deletes a profile owned by the current user'
        type: 'void'
        nickname: 'delete_profile'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to delete'
            required: true
            type: 'string'
            paramType: 'path'
        responseMessages:
          -
            code: 204
            message: 'Resource successfully deleted'
          -
            code: 400
            message: 'Invalid input'
            responseModel: 'ApiResponse'
          -
            code: 403
            message: 'Not authorized to delete the requested resource'
            responseModel: 'ApiResponse'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'ApiResponse'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'ApiResponse'
      -
        method: 'PATCH'
        summary: 'Update a profile'
        notes: 'Updates a profile administered by the current user'
        type: 'ApiResponse'
        nickname: 'update_profile'
        consumes:
          - 'application/json-patch+json'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to update'
            required: true
            type: 'string'
            paramType: 'path'
          -
            name: 'body'
            description: 'Requested modifications in JSON Patch format (see <a href="http://tools.ietf.org/html/rfc6902" title="RFC6902 - JSON Patch">RFC6902</a> and <a href="http://jsonapi.org/format/#updating-a-document" title="JSON API - Updating a Document (PATCH)">JSON API</a>)'
            required: true
            type: 'PatchOperations'
            paramType: 'body'
        responseMessages:
          -
            code: 200
            message: 'Resource successfully updated'
            responseModel: 'ApiResponse'
          -
            code: 403
            message: 'Not authorized to update the requested resource'
            responseModel: 'ApiResponse'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'ApiResponse'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'ApiResponse'
models:
  Sort:
    id: 'Sort'
    description: 'Sort order details indexed by resource name'
    required:
      - 'profiles'
    properties:
      profiles:
        type: 'array'
        description: 'Sort order for profile resources'
        uniqueItems: true
        items:
          type: 'string'
  Navigation:
    id: 'Navigation'
    description: 'Navigation details for this response'
    properties:
      first:
        type: 'string'
        description: 'URL for first set of results'
      prev:
        type: 'string'
        description: 'URL for previous set of results'
      next:
        type: 'string'
        description: 'URL for next set of results'
      last:
        type: 'string'
        description: 'URL for last set of results'
  Pagination:
    id: 'Pagination'
    description: 'Pagination details for this response'
    properties:
      limit:
        type: 'integer'
        format: 'int32'
        description: 'Maximum number of results to return (default = 8, maximum = 50)'
        minimum: 1
        maximum: 50
        defaultValue: 8
      offset:
        type: 'integer'
        format: 'int32'
        description: 'Starting index, 0-based (default = 0)'
        minimum: 0
        defaultValue: 0
      sort:
        $ref: 'Sort'
        description: 'Sort order, indexed by resource'
      navigation:
        $ref: 'Navigation'
        description: 'Navigation details for this response'
  Message:
    id: 'Message'
    description: 'A message generated by a request'
    required:
      - 'summary'
      - 'message_code'
    properties:
      target:
        type: 'string'
        description: 'Target of this message (field, object, etc.)'
      summary:
        type: 'string'
        description: 'Message summary'
      message_code:
        type: 'string'
        description: 'stori.es internal message code'
      detail_url:
        type: 'string'
        description: 'URL for message details'
  Metadata:
    id: 'Metadata'
    description: 'Metadata about this response'
    required:
      - 'self'
      - 'http_code'
      - 'status'
    properties:
      self:
        type: 'string'
        description: 'Full request URL'
      status:
        type: 'string'
        description: 'High-level status of response'
        enum:
          - 'success'
          - 'fail'
          - 'error'
      http_code:
        type: 'string'
        description: 'HTTP response status code'
      messages:
        type: 'array'
        description: 'Array of messages generated by request'
        items:
          $ref: 'Message'
      pagination:
        $ref: 'Pagination'
        description: 'Pagination details for this response'
  ResourceLink:
    id: 'ResourceLink'
    description: 'Metadata describing a resource'
    required:
      - 'href'
    properties:
      href:
        type: 'string'
        description: 'The URL of the resource'
  ResourceLinks:
    id: 'ResourceLinks'
    description: 'Metadata describing associated resources'
    required:
      - 'organization'
      - 'creator'
      - 'owner'
    properties:
      organization:
        $ref: 'ResourceLink'
        description: 'The organization this user profile is associated with'
      user:
        $ref: 'ResourceLink'
        description: 'The user this organization-specific profile is associated with'
      contacts:
        type: 'array'
        description: 'Metatdata describing contacts associated with this entity'
        items:
          $ref: 'ResourceLink'
      stories:
        type: 'array'
        description: 'Metadata describing stories associated with this entity'
        items: 
          $ref: 'ResourceLink'
      notes:
        type: 'array'
        description: 'Metadata describing note documents associated with this entity'
        items: 
          $ref: 'ResourceLink'
      creator:
        $ref: 'ResourceLink'
        description: 'Metadata describing the creator of this entity'
      owner:
        $ref: 'ResourceLink'
        description: 'Metadata describing the owner of this entity'
      administrators:
        type: 'array'
        description: 'Metadata describing the administrators of this entity'
        items:
          $ref: 'ResourceLink'
      curators:
        type: 'array'
        description: 'Metadata describing the curators of this entity'
        items:
          $ref: 'ResourceLink'
      readers:
        type: 'array'
        description: 'Metadata describing the readers of this entity'
        items:
          $ref: 'ResourceLink'
  Profile:
    id: 'Profile'
    description: 'The representation of a profile on the stori.es platform'
    required:
      - 'id'
      - 'path_segment'
      - 'links'
      - 'created_on'
      - 'updated_on'
    properties:
      id:
        type: 'string'
        description: 'The unique ID for this entity; format: /profiles/[organization path segment]/[profile path segment]'
      path_segment:
        type: 'string'
        description: 'The URL path segment uniquely identifying this profile within an organization; defaults to user handle; generated if undefined'
      given_name:
        type: 'string'
        description: 'The first name associated with this profile'
        maximum: 255
      surname:
        type: 'string'
        description: 'The last name associated with this profile'
        maximum: 255
      links:
        $ref: 'ResourceLinks'
        description: 'Metadata describing resources associated with this entity'
      created_on:
        type: 'string'
        format: 'date-time'
        description: 'The creation date and time for this entity, normalized to UTC (see <a href="http://tools.ietf.org/html/rfc3339" title="RFC3339 - Date and Time on the Internet">RFC3339</a>)'
      updated_on:
        type: 'string'
        format: 'date-time'
        description: 'The most recent modification date and time for this entity, normalized to UTC (see <a href="http://tools.ietf.org/html/rfc3339" title="RFC3339 - Date and Time on the Internet">RFC3339</a>)'
  ApiResponse:
    id: 'ApiResponse'
    description: 'The standard API response format for the stori.es platform; follows the <a href="http://jsonapi.org/" title="JSON API - A standard for building APIs in JSON">JSON API</a> standard'
    required:
      - 'meta'
      - 'profiles'
    properties:
      meta:
        $ref: 'Metadata'
        description: 'Metadata describing this response'
      profiles:
        type: 'array'
        description: 'Array of requested profile resources'
        items:
          $ref: 'Profile'
  ProfilePost:
    id: 'ProfilePost'
    description: 'The representation of a new profile to be added to the stori.es platform'
    required:
      - 'organization_id'
    properties:
      path_segment:
        type: 'string'
        description: 'The URL path segment uniquely identifying this profile within an organization; defaults to user handle; generated if undefined'
      organization_id:
        type: 'string'
        description: 'The ID of the organization associated with this entity'
      user_id:
        type: 'string'
        description: 'The ID of the user associated with this entity'
      given_name:
        type: 'string'
        description: 'The first name associated with this profile'
        maximum: 255
      surname:
        type: 'string'
        description: 'The last name associated with this profile'
        maximum: 255        
      contact_ids:
        type: 'array'
        description: 'The IDs of contacts associated with this entity'
        items: 
          type: 'string'
      story_ids:
        type: 'array'
        description: 'The IDs of stories associated with this entity'
        items: 
          type: 'string'
      note_ids:
        type: 'array'
        description: 'The IDs of note documents associated with this entity'
        items: 
          type: 'string'
      owner_id:
        type: 'string'
        description: 'The ID of the owner of this entity'        
  PatchOperation:
    id: 'PatchOperation'
    description: 'A JSON Patch operation (see <a href="http://tools.ietf.org/html/rfc6902" title="RFC6902 - JSON Patch">RFC6902</a> and <a href="http://jsonapi.org/format/#updating-a-document" title="JSON API - Updating a Document">JSON API</a>)'
    required:
      - 'op'
      - 'path'
    properties:
      op:
        type: 'string'
        description: 'The operation to perform'
        enum:
          - 'add'
          - 'remove'
          - 'replace'
          - 'move'
          - 'copy'
          - 'test'
      path:
        type: 'string'
        description: 'A JSON Pointer value (see <a href="http://tools.ietf.org/html/rfc6901" title="RFC6901 - JSON Pointer">RFC6901</a>) referencing a location within the target document where the operation is to be performed'
      value:
        type: 'string'
        description: 'The value to patch'
      from:
        type: 'string'
        description: 'A JSON Pointer value (see <a href="http://tools.ietf.org/html/rfc6901" title="RFC6901 - JSON Pointer">RFC6901</a>) referencing a location within the target document to move or copy'
  PatchOperations:
    id: 'PatchOperations'
    description: 'The representation of requested modifications to an entity on the stori.es platform'
    required:
      - 'operations'
    properties:
      operations:
        type: 'array'
        description: 'The set of operations composing requested modifications to a target entity'
        items:
          $ref: 'PatchOperation'