apiVersion: 1
swaggerVersion: 1.2
basePath: 'http://www.stori.es/api/website/listings'
description: 'Operations for profiles'
resourcePath: '/profiles'
produces:
  - 'application/json'
consumes:
  - 'application/json'
apis:
  -
    path: '/profiles'
    operations:          
      -
        method: 'POST'
        summary: 'Create a new profile'
        notes: 'Creates a new profile and returns it. Declares the resource URL in the Location header.'
        type: 'Profile'
        nickname: 'create_profile'
        parameters:
          -
            name: 'body'
            description: 'The new profile to be created'
            required: true
            type: 'Profile'
            paramType: 'body'
        responseMessages:
          -
            code: 201
            message: 'Resource successfully created'
            responseModel: 'Profile'
          -
            code: 400
            message: 'Invalid input'
            responseModel: 'Error'
          -
            code: 403
            message: 'Not authorized to create the requested resource'
            responseModel: 'Error'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'Error'
  -
    path: '/profiles/{profile_id}'
    operations:
      -
        method: 'GET'
        summary: 'Retrieve a specific profile'
        notes: 'Returns a specific profile accessible to the current user'
        type: 'Profile'
        nickname: 'get_profile'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to retrieve'
            required: true
            type: 'integer'
            format: 'int64'
            paramType: 'path'
        responseMessages:
          -
            code: 200
            message: 'Resource successfully retrieved'
            responseModel: 'Profile'
          -
            code: 403
            message: 'Not authorized to access the requested resource'
            responseModel: 'Error'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'Error'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'Error'
      -
        method: 'DELETE'
        summary: 'Delete a profile'
        notes: 'Deletes a profile owned by the current user'
        type: 'void'
        nickname: 'delete_profile'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to delete'
            required: true
            type: 'integer'
            format: 'int64'
            paramType: 'path'
        responseMessages:
          -
            code: 204
            message: 'Resource successfully deleted'
          -
            code: 400
            message: 'Invalid input'
            responseModel: 'Error'
          -
            code: 403
            message: 'Not authorized to delete the requested resource'
            responseModel: 'Error'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'Error'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'Error'
      -
        method: 'PATCH'
        summary: 'Update a profile'
        notes: 'Updates a profile administered by the current user'
        type: 'Profile'
        nickname: 'update_profile'
        parameters:
          -
            name: 'profile_id'
            description: 'The ID of the profile to update'
            required: true
            type: 'integer'
            format: 'int64'
            paramType: 'path'
          -
            name: 'body'
            description: 'The updated profile'
            required: true
            type: 'Profile'
            paramType: 'body'
        responseMessages:
          -
            code: 200
            message: 'Resource successfully updated'
            responseModel: 'Profile'
          -
            code: 403
            message: 'Not authorized to update the requested resource'
            responseModel: 'Error'
          -
            code: 404
            message: 'Resource not found'
            responseModel: 'Error'
          -
            code: 503
            message: 'Service is currently unavailable'
            responseModel: 'Error'
models:
  Profile:
    id: 'Profile'
    description: 'The representation of a profile on the stori.es platform'
    required:
       - 'id'
    properties:
      id:
        type: 'string'
        description: 'The unique ID for this entity'
      title:
        type: 'string'
        description: 'The title of this entity'
      path:
        type: 'string'
        description: 'The URL path fragment associated with this entity; its namespace'
      permalink:
        type: 'string'
        description: 'The URL of this entity on the stori.es platform'
      given_name:
        type: 'string'
        description: 'The first name associated with this profile'
        maximum: 255
      surname:
        type: 'string'
        description: 'The last name associated with this profile'
        maximum: 255
      note_ids:
        type: 'array'
        description: 'The IDs of notes associated with this entity'
        items: 
          type: 'integer'
          format: 'int64'
      link_ids:
        type: 'array'
        description: 'The IDs of links associated with this entity'
        items: 
          type: 'integer'
          format: 'int64'
  Error:
    id: 'Error'
    description: 'The representation of a stori.es API error'
    required:
       - 'http_status_code'
       - 'error_code'
       - 'summary'
    properties:
      http_status_code:
        type: 'integer'
        format: 'int64'
        description: 'The HTTP status code'
      error_code:
        type: 'string'
        description: 'The stori.es internal error code'
      summary:
        type: 'string'
        description: 'A brief summary of the error encountered'
      detail_url:
        type: 'string'
        description: 'A URL for developers containing more detail about the error'